SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
COMMENT ON SCHEMA "public" IS 'standard public schema';
CREATE EXTENSION IF NOT EXISTS "pgroonga" WITH SCHEMA "public";
CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE OR REPLACE FUNCTION "public"."get_task_counts"() RETURNS TABLE("total_count" bigint, "completed_count" bigint)
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT COUNT(*), COUNT(*) FILTER (WHERE completed = true) FROM tasks;
END;
$$;
ALTER FUNCTION "public"."get_task_counts"() OWNER TO "postgres";
SET default_tablespace = '';
SET default_table_access_method = "heap";
CREATE TABLE IF NOT EXISTS "public"."tasks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "text" "text",
    "completed" boolean DEFAULT false,
    "user_id" "uuid",
    "deadline" timestamp with time zone,
    "priority" "text" DEFAULT 'low'::"text" NOT NULL
);
ALTER TABLE "public"."tasks" OWNER TO "postgres";
ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;
CREATE POLICY "Enable delete for users based on user_id" ON "public"."tasks" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Enable insert for authenticated users only" ON "public"."tasks" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Enable select for users based on user_id" ON "public"."tasks" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
CREATE POLICY "Enable update for users based on user_id" ON "public"."tasks" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));
ALTER TABLE "public"."tasks" ENABLE ROW LEVEL SECURITY;
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON FUNCTION "public"."get_task_counts"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_task_counts"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_task_counts"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text", "arguments" "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text", "arguments" "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text", "arguments" "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_command"("groongacommand" "text", "arguments" "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_command_escape_value"("value" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_command_escape_value"("value" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_command_escape_value"("value" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_command_escape_value"("value" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_contain_varchar_array"(character varying[], character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_contain_varchar_array"(character varying[], character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_contain_varchar_array"(character varying[], character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_contain_varchar_array"(character varying[], character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_text_array"("targets" "text"[], "query" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_text_array"("targets" "text"[], "query" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_text_array"("targets" "text"[], "query" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_text_array"("targets" "text"[], "query" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_varchar_array"("targets" character varying[], "query" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_varchar_array"("targets" character varying[], "query" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_varchar_array"("targets" character varying[], "query" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_query_varchar_array"("targets" character varying[], "query" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text"("target" "text", "other" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text"("target" "text", "other" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text"("target" "text", "other" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text"("target" "text", "other" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar"("target" character varying, "other" character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar"("target" character varying, "other" character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar"("target" character varying, "other" character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar"("target" character varying, "other" character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_equal_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" boolean) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" boolean) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" real) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" real) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" real) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" real) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" double precision) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" double precision) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" double precision) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" double precision) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" smallint) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" smallint) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" smallint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" smallint) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" bigint) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" bigint) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp without time zone) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp without time zone) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp without time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp without time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp with time zone) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp with time zone) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text", "special_characters" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text", "special_characters" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text", "special_characters" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_escape"("value" "text", "special_characters" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_flush"("indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_flush"("indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_flush"("indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_flush"("indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_handler"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_handler"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_handler"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_handler"("internal") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[], "indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[], "indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[], "indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("targets" "text"[], "keywords" "text"[], "indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_highlight_html"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnindex" integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnindex" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnindex" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnindex" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnname" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnname" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnname" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_index_column_name"("indexname" "cstring", "columnname" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_is_writable"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_is_writable"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_is_writable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_is_writable"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text"("text", "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text"("text", "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text"("text", "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text"("text", "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text_array"("text"[], "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text_array"("text"[], "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text_array"("text"[], "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_text_array"("text"[], "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_varchar"(character varying, character varying[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_varchar"(character varying, character varying[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_varchar"(character varying, character varying[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_in_varchar"(character varying, character varying[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_jsonb"("jsonb", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_jsonb"("jsonb", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_jsonb"("jsonb", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_jsonb"("jsonb", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_byte"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_positions_character"("target" "text", "keywords" "text"[], "indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text"[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text"[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text"[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text"[], "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_query"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_regexp"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_script_jsonb"("jsonb", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_script_jsonb"("jsonb", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_script_jsonb"("jsonb", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_script_jsonb"("jsonb", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text"[], "term" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text"[], "term" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text"[], "term" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text"[], "term" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying[], "term" character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying[], "term" character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying[], "term" character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying[], "term" character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text", "term" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text", "term" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text", "term" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" "text", "term" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying, "term" character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying, "term" character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying, "term" character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_term"("target" character varying, "term" character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array"("text"[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array"("text"[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array"("text"[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array"("text"[], "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition_with_scorers"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition_with_scorers"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition_with_scorers"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_array_condition_with_scorers"("target" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_match_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text", "normalizername" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text", "normalizername" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text", "normalizername" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_normalize"("target" "text", "normalizername" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_not_prefix_in_text"("text", "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_not_prefix_in_text"("text", "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_not_prefix_in_text"("text", "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_not_prefix_in_text"("text", "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text"("text", "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text"("text", "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text"("text", "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text"("text", "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text_array"("text"[], "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text_array"("text"[], "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text_array"("text"[], "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_text_array"("text"[], "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar"(character varying, character varying[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar"(character varying, character varying[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar"(character varying, character varying[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar"(character varying, character varying[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar_array"(character varying[], character varying[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar_array"(character varying[], character varying[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar_array"(character varying[], character varying[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_in_varchar_array"(character varying[], character varying[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text"("text", "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text"("text", "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text"("text", "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text"("text", "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text_array"("text"[], "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text_array"("text"[], "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text_array"("text"[], "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_text_array"("text"[], "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar"(character varying, character varying[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar"(character varying, character varying[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar"(character varying, character varying[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar"(character varying, character varying[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar_array"(character varying[], character varying[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar_array"(character varying[], character varying[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar_array"(character varying[], character varying[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_in_varchar_array"(character varying[], character varying[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text_array"("text"[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text_array"("text"[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text_array"("text"[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_text_array"("text"[], "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar_array"(character varying[], character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar_array"(character varying[], character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar_array"(character varying[], character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_rk_varchar_array"(character varying[], character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_array"("text"[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_array"("text"[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_array"("text"[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_array"("text"[], "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_condition"("text", "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_condition"("text", "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_condition"("text", "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_text_condition"("text", "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_array"(character varying[], character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_array"(character varying[], character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_array"(character varying[], character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_array"(character varying[], character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_condition"("target" character varying, "conditoin" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_condition"("target" character varying, "conditoin" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_condition"("target" character varying, "conditoin" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_prefix_varchar_condition"("target" character varying, "conditoin" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_escape"("query" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_escape"("query" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_escape"("query" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_escape"("query" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_expand"("tablename" "cstring", "termcolumnname" "text", "synonymscolumnname" "text", "query" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_expand"("tablename" "cstring", "termcolumnname" "text", "synonymscolumnname" "text", "query" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_expand"("tablename" "cstring", "termcolumnname" "text", "synonymscolumnname" "text", "query" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_expand"("tablename" "cstring", "termcolumnname" "text", "synonymscolumnname" "text", "query" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_extract_keywords"("query" "text", "index_name" "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_extract_keywords"("query" "text", "index_name" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_extract_keywords"("query" "text", "index_name" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_extract_keywords"("query" "text", "index_name" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text"("text", "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text"("text", "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text"("text", "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text"("text", "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text_array"("text"[], "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text_array"("text"[], "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text_array"("text"[], "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_text_array"("text"[], "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_varchar"(character varying, character varying[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_varchar"(character varying, character varying[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_varchar"(character varying, character varying[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_in_varchar"(character varying, character varying[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_jsonb"("jsonb", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_jsonb"("jsonb", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_jsonb"("jsonb", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_jsonb"("jsonb", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array"("text"[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array"("text"[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array"("text"[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array"("text"[], "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition_with_scorers"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition_with_scorers"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition_with_scorers"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_array_condition_with_scorers"("targets" "text"[], "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition"("target" "text", "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_text_condition_with_scorers"("target" "text", "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_query_varchar_condition_with_scorers"("target" character varying, "condition" "public"."pgroonga_full_text_search_condition_with_scorers") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_text"("text", "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_text"("text", "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_text"("text", "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_text"("text", "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_varchar"(character varying, character varying[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_varchar"(character varying, character varying[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_varchar"(character varying, character varying[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_in_varchar"(character varying, character varying[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_text"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_text"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_text"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_text"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_varchar"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_varchar"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_varchar"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_regexp_varchar"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_jsonb_objects"("result" "jsonb") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_jsonb_objects"("result" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_jsonb_objects"("result" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_jsonb_objects"("result" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_recordset"("result" "jsonb") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_recordset"("result" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_recordset"("result" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_result_to_recordset"("result" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("row" "record") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("row" "record") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("row" "record") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("row" "record") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("tableoid" "oid", "ctid" "tid") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("tableoid" "oid", "ctid" "tid") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("tableoid" "oid", "ctid" "tid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_score"("tableoid" "oid", "ctid" "tid") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_script_jsonb"("jsonb", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_script_jsonb"("jsonb", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_script_jsonb"("jsonb", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_script_jsonb"("jsonb", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text_array"("text"[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text_array"("text"[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text_array"("text"[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_script_text_array"("text"[], "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_script_varchar"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_script_varchar"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_script_varchar"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_script_varchar"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_set_writable"("newwritable" boolean) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_set_writable"("newwritable" boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_set_writable"("newwritable" boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_set_writable"("newwritable" boolean) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text"("text", "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text_array"("text"[], "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text_array"("text"[], "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text_array"("text"[], "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_text_array"("text"[], "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_varchar"(character varying, character varying) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_varchar"(character varying, character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_varchar"(character varying, character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_similar_varchar"(character varying, character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_snippet_html"("target" "text", "keywords" "text"[], "width" integer) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_snippet_html"("target" "text", "keywords" "text"[], "width" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_snippet_html"("target" "text", "keywords" "text"[], "width" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_snippet_html"("target" "text", "keywords" "text"[], "width" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_table_name"("indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_table_name"("indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_table_name"("indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_table_name"("indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_tokenize"("target" "text", VARIADIC "options" "text"[]) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_tokenize"("target" "text", VARIADIC "options" "text"[]) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_tokenize"("target" "text", VARIADIC "options" "text"[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_tokenize"("target" "text", VARIADIC "options" "text"[]) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_vacuum"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_vacuum"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_vacuum"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_vacuum"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"("indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"("indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"("indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_apply"("indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring") TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("block" bigint, "offset" bigint) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("block" bigint, "offset" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("block" bigint, "offset" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("block" bigint, "offset" bigint) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring", "block" bigint, "offset" bigint) TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring", "block" bigint, "offset" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring", "block" bigint, "offset" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_set_applied_position"("indexname" "cstring", "block" bigint, "offset" bigint) TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_status"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_status"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_status"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_status"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"() TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"() TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"("indexname" "cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"("indexname" "cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"("indexname" "cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pgroonga_wal_truncate"("indexname" "cstring") TO "service_role";
GRANT ALL ON TABLE "public"."tasks" TO "anon";
GRANT ALL ON TABLE "public"."tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks" TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";
RESET ALL;
