name: Deploy to Supabase and Vercel

on:
  push:
    branches:
      - main
    paths:
      - supabase/migrations/**

jobs:
  migrate:
    name: Supabase マイグレーションの実行
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Supabase CLI のセットアップ
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase プロジェクトにリンク
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: マイグレーションの実行
        run: supabase db push

  deploy_vercel:
    name: Vercel へのデプロイ
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Vercel へのデプロイ
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
